// Interaction check for Home study E rev 4 + Explore (rev 5) … Journeys (rev 8). Run from a folder with playwright installed:
//   CHROMIUM=$(which chromium) node design/studies/2026-10-05-home-e/check.mjs
// Fails (exit 1) on any runtime error or broken rule.
import { chromium } from 'playwright';
import { fileURLToPath } from 'url';
const U = new URL('./home.html', import.meta.url).href;
const b = await chromium.launch(process.env.CHROMIUM ? { executablePath: process.env.CHROMIUM } : {});
const errs = [], fail = m => errs.push(m);
const pg = async vp => { const p = await b.newPage({ viewport: vp }); p.on('pageerror', e => fail('runtime: ' + e.message)); await p.goto(U); await p.waitForTimeout(800); return p; };
let p = await pg({ width: 1440, height: 900 });
await p.click('#wv', { position: { x: 215, y: 12 } });
if (Math.abs(await p.evaluate(() => st.t / cur().d) - .5) > .05) fail('scrubber click should seek to ~50%');
await p.click('#digGo'); await p.waitForTimeout(400);
if (!(await p.evaluate(() => DG.open && !st.on))) fail('Dig must open and pause main playback');
for (const k of ['ArrowRight', 'ArrowLeft', 'ArrowRight']) { await p.keyboard.press(k); await p.waitForTimeout(400); }
if (JSON.stringify(await p.evaluate(() => SRC.dug.q)) !== '["dg0","dg2"]') fail('Keep must add to Dug in order');
await p.click('#toastBtn'); await p.waitForTimeout(300);
if (JSON.stringify(await p.evaluate(() => [SRC.dug.q, DG.i])) !== '[["dg0"],2]') fail('Undo must revert the last decision');
for (let j = 0; j < 8; j++) { await p.keyboard.press('ArrowLeft'); await p.waitForTimeout(320); }
if (!(await p.evaluate(() => DG.i === 10 && !!document.getElementById('dgPlayDug')))) fail('stack must end after 10 with Play Dug');
await p.click('#dgPlayDug'); await p.waitForTimeout(400);
if (JSON.stringify(await p.evaluate(() => [st.src, st.on, SRC.dug.q.length])) !== '["dug",true,1]') fail('Play Dug must play the Dug source');
await p.evaluate(() => { st.i = SRC.dug.q.length - 1; st.t = cur().d - .3; }); await p.waitForTimeout(700);
if (await p.evaluate(() => st.on)) fail('natural end of a source must stop, not expand');
await p.close();
p = await pg({ width: 390, height: 844 });
const over = await p.evaluate(() => [...document.querySelectorAll('.tb *, .bar *, .tabs *')].filter(e => { const r = e.getBoundingClientRect(); return r.width && r.right > innerWidth + 1 && getComputedStyle(e).display !== 'none'; }).length);
if (over) fail(over + ' phone chrome elements overflow at 390px');
await p.click('.tabs [data-tab=Explore]'); await p.waitForTimeout(400);
if (!(await p.evaluate(() => XP.view === 'explore' && document.querySelector('.tabs .on').dataset.tab === 'Explore'))) fail('Explore tab must open Explore');
const xo = await p.evaluate(() => [...document.querySelectorAll('#xp *')].filter(e => { const r = e.getBoundingClientRect(); return r.width && r.right > innerWidth + 1 && !e.closest('.xp-rc, .xg') && getComputedStyle(e).display !== 'none'; }).length);
if (xo) fail(xo + ' Explore elements overflow at 390px');
if (await p.evaluate(() => $('main').scrollWidth > $('main').clientWidth + 1)) fail('Explore must not scroll sideways at 390px');
await p.click('#xdGo'); await p.waitForTimeout(400);
if (!(await p.evaluate(() => DG.open))) fail('Dig must open from Explore');
await p.click('#digX'); await p.waitForTimeout(400);
if (!(await p.evaluate(() => !DG.open && document.querySelector('.tabs .on').dataset.tab === 'Explore'))) fail('closing Dig must return to Explore');
await p.close();
p = await pg({ width: 1440, height: 900 });
await p.click('.side [data-nav=explore]'); await p.waitForTimeout(300);
await p.click('[data-tu="tempo:slow"]'); await p.click('[data-tu="feel:dark"]');
if (!(await p.evaluate(() => tuMatch().every(k => S[k].bpm < 95 && /min/.test(S[k].key))))) fail('Tune a mix must only include matching songs');
await p.click('#tuPlay'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => st.src === 'tu_slow_any_dark' && st.on))) fail('Play mix must play the tuned source');
await p.click('#tuPlay'); if (await p.evaluate(() => st.on)) fail('Play mix on the live tune must pause, not restart');
const empty = await p.evaluate(() => { for (const a of ['slow','mid','fast']) for (const v of ['vox','inst']) for (const f of ['bright','dark']) { Object.assign(XP.tu, { tempo: a, voice: v, feel: f }); if (!tuMatch().length) return [a, v, f]; } return null; });
if (empty) { for (const [d, v] of [['tempo', empty[0]], ['voice', empty[1]], ['feel', empty[2]]]) await p.click(`[data-tu="${d}:${v}"]`); }
if (empty && !(await p.evaluate(() => tuMatch().length === 0 && document.getElementById('tuPlay').disabled))) fail('an empty tune must disable Play');
const seed = await p.evaluate(() => XP.seed); await p.click('.gfc'); await p.waitForTimeout(200);
if (!(await p.evaluate(s => st.src.startsWith('gf_t_') && XP.seed === s && document.querySelector('.gfc').classList.contains('on'), seed))) fail('Go from must play and keep its seed while playing');
await p.evaluate(() => { st.i = 1; onTrack(true); }); await p.waitForTimeout(200);
await p.click('#rhHop'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => XP.trail.length === 2 && XP.pin === XP.trail[1] && XP.seed === XP.pin))) fail('Hop must extend the Rabbit hole trail and re-seed Go from');
const before = await p.evaluate(() => st.src); await p.click('#rhSave'); await p.waitForTimeout(150);
if (!(await p.evaluate(b => st.src === b && XP.saved.some(x => x.k.startsWith('rh_')) && !!document.querySelector('.li.svd'), before))) fail('Save as playlist must add a playlist without changing playback');
await p.evaluate(() => { st.i = SRC[st.src].q.length - 1; st.t = cur().d - .3; }); await p.waitForTimeout(700);
if (await p.evaluate(() => st.on)) fail('a Go-from mix must stop at its end');
await p.click('[data-tu="tempo:slow"]'); await p.click('[data-tu="voice:any"]'); await p.click('[data-tu="feel:dark"]'); await p.click('#tuSave'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => !!SRC.st_slow_any_dark && XP.saved.some(x => x.k === 'st_slow_any_dark') && /Saved/.test($('tuSave').textContent)))) fail('Save tune must save once and show Saved');
await p.click('[data-tu="tempo:any"]'); await p.click('[data-tune="st_slow_any_dark"]');
if (!(await p.evaluate(() => XP.tu.tempo === 'slow' && XP.tu.feel === 'dark'))) fail('a saved tune chip must restore its dials');
await p.click('#xpIn'); await p.keyboard.type('gray');
if (!(await p.evaluate(() => document.body.classList.contains('xp-searching') && SR[0] && SR[0].t === 'Moni Gray'))) fail('search must show results in place with the best match first');
await p.keyboard.press('Escape'); await p.keyboard.type('qwzx');
if (!(await p.evaluate(() => !!document.querySelector('.sr-none')))) fail('no-results state must show');
await p.keyboard.press('Escape'); await p.keyboard.press('Escape');
if (await p.evaluate(() => document.body.classList.contains('xp-searching'))) fail('Esc twice must leave search');
await p.keyboard.press('Control+k');
if (!(await p.evaluate(() => document.activeElement.id === 'xpIn' && !$('pal').classList.contains('open')))) fail('in Explore, Ctrl+K must focus the search field');
await p.close();
/* Now Playing page (rev 7) */
p = await pg({ width: 1440, height: 900 });
await p.keyboard.press('l'); await p.waitForTimeout(300);
if (!(await p.evaluate(() => $('np').classList.contains('open') && !!document.querySelector('.npt')))) fail('L must open the Now Playing page with tabs');
await p.evaluate(() => { st.uq.push('m2'); render(); }); await p.keyboard.press('2'); await p.waitForTimeout(200);
const upn = await p.evaluate(() => [...document.querySelectorAll('#npP button.npq[data-src]')].map(e => e.dataset.src));
if (!upn.length || upn.some(x => x !== 'late')) fail('Up next must list only the active source after the user queue');
if (!(await p.evaluate(() => /Playback stops here/.test($('npP').textContent) && /Next in queue/.test($('npP').textContent)))) fail('Up next must show the user queue and the honest end of source');
await p.click('[data-uqx="0"]'); await p.waitForTimeout(100);
if (await p.evaluate(() => st.uq.length)) fail('removing from the queue must work');
await p.click('#toastBtn'); if (!(await p.evaluate(() => st.uq[0] === 'm2'))) fail('Undo must restore the queue item');
await p.keyboard.press('3'); await p.waitForTimeout(150);
const crBtn = await p.$('[data-crp]'); if (!crBtn) fail('Credits must offer Play their credits'); else { await crBtn.click(); await p.waitForTimeout(150); if (!(await p.evaluate(() => st.src.startsWith('cr_') && SRC[st.src].q.includes(curK())))) fail('Play their credits must play that person\'s songs'); }
await p.keyboard.press('Escape'); await p.waitForTimeout(200);
if (await p.evaluate(() => $('np').classList.contains('open'))) fail('Esc must close Now Playing');
await p.close();
p = await pg({ width: 390, height: 844 });
await p.click('.bar .cur'); await p.waitForTimeout(400);
if (!(await p.evaluate(() => document.body.classList.contains('np-open') && getComputedStyle(document.querySelector('.bar')).visibility === 'hidden' && getComputedStyle(document.querySelector('.npctl')).display !== 'none'))) fail('phone Now Playing must be full screen with its own controls');
const on0 = await p.evaluate(() => st.on); await p.click('.nppp'); if ((await p.evaluate(() => st.on)) === on0) fail('phone play button must toggle playback');
const bx = await p.$eval('#npSk', e => { const r = e.getBoundingClientRect(); return [r.left + r.width * .75, r.top + r.height / 2]; }); await p.mouse.click(bx[0], bx[1]);
if (Math.abs(await p.evaluate(() => st.t / cur().d) - .75) > .05) fail('phone scrubber must seek');
const npo = await p.evaluate(() => $('np').scrollWidth > $('np').clientWidth + 1); if (npo) fail('phone Now Playing must not scroll sideways');
await p.click('#npX'); await p.waitForTimeout(300); if (await p.evaluate(() => document.body.classList.contains('np-open'))) fail('close must leave Now Playing');
await p.close();
// rev 8: Journeys (D-069)
p = await pg({ width: 1440, height: 900 });
await p.click('.side .nav [data-nav=journeys]'); await p.waitForTimeout(300);
if (!(await p.evaluate(() => document.body.classList.contains('v-jv') && !!document.querySelector('#jv .jmap') && getComputedStyle($('jv')).display !== 'none'))) fail('Journeys nav must open the genre page with the map');
await p.click('.jsta[data-jart="3"]'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => JV.ai === 3 && !!document.querySelector('.jah')))) fail('map station must open the Artist Journey');
await p.click('.jah [data-jpl="3"]'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => st.src === 'journey' && st.on && curK() === 'm1'))) fail('Start must play the artist Journey from the first unheard song');
await p.evaluate(() => { ['m2', 'm3', 'm4'].forEach(k => st.jHeard.add(k)); startSrc('journey', 4); st.t = cur().d - .3; }); await p.waitForTimeout(700);
await p.evaluate(() => { st.t = cur().d - .3; }); await p.waitForTimeout(800);
const fin = await p.evaluate(() => { const G = JR.G['Hip-Hop']; return [st.on, st.src, jDone(G, G.A[3]), !!G.A[3].stamp, /stamp collected/.test($('toast').textContent), SRC.journey.q.includes(curK())]; });
if (fin[0] || fin[1] !== 'journey' || !fin[5]) fail('end of an artist must stop, never autoplay the next artist: ' + JSON.stringify(fin));
if (!fin[3] || !fin[4]) fail('finishing an artist must give a stamp + toast: ' + JSON.stringify(fin));
await p.close();
p = await pg({ width: 1440, height: 900 });
await p.evaluate(() => setView('journeys'));
const h0 = await p.evaluate(() => st.jHeard.size);
await p.click('#jv [data-skip="4"]'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => JR.G['Hip-Hop'].cur === 4))) fail('Skip ahead must move the current artist');
await p.click('#toastBtn'); await p.waitForTimeout(150);
if (!(await p.evaluate(h => JR.G['Hip-Hop'].cur === 3 && st.jHeard.size === h, h0))) fail('Undo skip must restore, progress kept');
await p.click('#jv .jh [data-src^="top_"]'); await p.waitForTimeout(300);
if (!(await p.evaluate(h => st.src.startsWith('top_') && st.jHeard.size === h && JR.G['Hip-Hop'].cur === 3, h0))) fail('Play top mix must not change Journey progress (D-038)');
await p.click('#jv .jh-a [data-jnav=picker]'); await p.waitForTimeout(250);
await p.click('.pk-t[data-pk="Jazz"]'); await p.click('[data-pace="ess"]'); await p.click('#pkGo'); await p.waitForTimeout(250);
if (!(await p.evaluate(h => JV.g === 'Jazz' && JR.G.Jazz.pace === 'ess' && JR.active === 'Jazz' && st.jHeard.size === h && JR.G.Jazz.A.every(a => jPace(JR.G.Jazz, a).length <= 5), h0))) fail('Change genre must switch Journey, apply pace, erase nothing');
await p.click('#jv [data-meet="1"]'); await p.waitForTimeout(300);
if (!(await p.evaluate(() => $('modal').classList.contains('meetm') && !st.on))) fail('Meet must open the 15 s hook and pause main playback');
await p.click('#mtGo'); await p.waitForTimeout(250);
if (!(await p.evaluate(() => st.src === jKey('Jazz', 1) && st.on && JR.G.Jazz.cur === 1))) fail('Start from Meet must make that artist current and play');
await p.fill('#jIn', 'zzzz'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => /Nothing in the Jazz Journey/.test($('jv').textContent)))) fail('Journey search must show an honest no-results state');
await p.close();
p = await pg({ width: 390, height: 844 });
await p.click('.tabs [data-tab=Journeys]'); await p.waitForTimeout(300);
if (!(await p.evaluate(() => document.body.classList.contains('v-jv') && document.querySelector('.tabs .on').dataset.tab === 'Journeys'))) fail('Journeys tab must open Journeys');
for (const ai of [null, 3]) { await p.evaluate(a => setView('journeys', { ai: a ?? undefined }), ai); await p.waitForTimeout(200);
  const o = await p.evaluate(() => document.documentElement.scrollWidth > innerWidth || $('main').scrollWidth > $('main').clientWidth + 1); if (o) fail('Journeys must not scroll sideways at 390px (ai=' + ai + ')'); }
await p.close();
await b.close();
console.log(errs.length ? 'FAIL\n' + errs.join('\n') : 'PASS: Journeys (map, artist page, end stops + stamp, skip/undo, top mix, picker + pace, Meet, search, phone), scrubber, Dig flow, Undo, end-of-stack, Play Dug, source end stops, phone chrome, Explore tab + overflow, Dig from Explore, Tune a mix, Go from, Rabbit hole, Save tune, search page, Now Playing (tabs, Up next, queue remove/Undo, credits, phone controls)');
process.exit(errs.length ? 1 : 0);
