// Interaction check for Home study E rev 4 + Explore (rev 5) … Journeys (rev 8). Run from a folder with playwright installed:
//   CHROMIUM=$(which chromium) node design/studies/2026-10-05-home-e/check.mjs
// Fails (exit 1) on any runtime error or broken rule.
import { chromium } from 'playwright';
import { fileURLToPath } from 'url';
const U = new URL('./home.html', import.meta.url).href;
const b = await chromium.launch(process.env.CHROMIUM ? { executablePath: process.env.CHROMIUM } : {});
const errs = [], fail = m => errs.push(m);
const pg = async vp => { const p = await b.newPage({ viewport: vp }); p.on('pageerror', e => fail('runtime: ' + e.message)); await p.goto(U); await p.waitForTimeout(800); return p; };
let p = await pg({ width: 1440, height: 900 });
await p.click('#wv', { position: { x: 215, y: 12 } });
if (Math.abs(await p.evaluate(() => st.t / cur().d) - .5) > .05) fail('scrubber click should seek to ~50%');
await p.click('#digGo'); await p.waitForTimeout(400);
if (!(await p.evaluate(() => DG.open && !st.on))) fail('Dig must open and pause main playback');
for (const k of ['ArrowRight', 'ArrowLeft', 'ArrowRight']) { await p.keyboard.press(k); await p.waitForTimeout(400); }
if (JSON.stringify(await p.evaluate(() => SRC.dug.q)) !== '["dg0","dg2"]') fail('Keep must add to Dug in order');
await p.click('#toastBtn'); await p.waitForTimeout(300);
if (JSON.stringify(await p.evaluate(() => [SRC.dug.q, DG.i])) !== '[["dg0"],2]') fail('Undo must revert the last decision');
for (let j = 0; j < 8; j++) { await p.keyboard.press('ArrowLeft'); await p.waitForTimeout(320); }
if (!(await p.evaluate(() => DG.i === 10 && !!document.getElementById('dgPlayDug')))) fail('stack must end after 10 with Play Dug');
await p.click('#dgPlayDug'); await p.waitForTimeout(400);
if (JSON.stringify(await p.evaluate(() => [st.src, st.on, SRC.dug.q.length])) !== '["dug",true,1]') fail('Play Dug must play the Dug source');
await p.evaluate(() => { st.i = SRC.dug.q.length - 1; st.t = cur().d - .3; }); await p.waitForTimeout(700);
if (await p.evaluate(() => st.on)) fail('natural end of a source must stop, not expand');
await p.close();
p = await pg({ width: 390, height: 844 });
const over = await p.evaluate(() => [...document.querySelectorAll('.tb *, .bar *, .tabs *')].filter(e => { const r = e.getBoundingClientRect(); return r.width && r.right > innerWidth + 1 && getComputedStyle(e).display !== 'none'; }).length);
if (over) fail(over + ' phone chrome elements overflow at 390px');
await p.click('.tabs [data-tab=Explore]'); await p.waitForTimeout(400);
if (!(await p.evaluate(() => XP.view === 'explore' && document.querySelector('.tabs .on').dataset.tab === 'Explore'))) fail('Explore tab must open Explore');
const xo = await p.evaluate(() => [...document.querySelectorAll('#xp *')].filter(e => { const r = e.getBoundingClientRect(); return r.width && r.right > innerWidth + 1 && !e.closest('.xp-rc, .xg') && getComputedStyle(e).display !== 'none'; }).length);
if (xo) fail(xo + ' Explore elements overflow at 390px');
if (await p.evaluate(() => $('main').scrollWidth > $('main').clientWidth + 1)) fail('Explore must not scroll sideways at 390px');
await p.click('#xdGo'); await p.waitForTimeout(400);
if (!(await p.evaluate(() => DG.open))) fail('Dig must open from Explore');
await p.click('#digX'); await p.waitForTimeout(400);
if (!(await p.evaluate(() => !DG.open && document.querySelector('.tabs .on').dataset.tab === 'Explore'))) fail('closing Dig must return to Explore');
await p.close();
p = await pg({ width: 1440, height: 900 });
await p.click('.side [data-nav=explore]'); await p.waitForTimeout(300);
await p.click('[data-tu="tempo:slow"]'); await p.click('[data-tu="feel:dark"]');
if (!(await p.evaluate(() => tuMatch().every(k => S[k].bpm < 95 && /min/.test(S[k].key))))) fail('Tune a mix must only include matching songs');
await p.click('#tuPlay'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => st.src === 'tu_slow_any_dark' && st.on))) fail('Play mix must play the tuned source');
await p.click('#tuPlay'); if (await p.evaluate(() => st.on)) fail('Play mix on the live tune must pause, not restart');
const empty = await p.evaluate(() => { for (const a of ['slow','mid','fast']) for (const v of ['vox','inst']) for (const f of ['bright','dark']) { Object.assign(XP.tu, { tempo: a, voice: v, feel: f }); if (!tuMatch().length) return [a, v, f]; } return null; });
if (empty) { for (const [d, v] of [['tempo', empty[0]], ['voice', empty[1]], ['feel', empty[2]]]) await p.click(`[data-tu="${d}:${v}"]`); }
if (empty && !(await p.evaluate(() => tuMatch().length === 0 && document.getElementById('tuPlay').disabled))) fail('an empty tune must disable Play');
const seed = await p.evaluate(() => XP.seed); await p.click('.gfc'); await p.waitForTimeout(200);
if (!(await p.evaluate(s => st.src.startsWith('gf_t_') && XP.seed === s && document.querySelector('.gfc').classList.contains('on'), seed))) fail('Go from must play and keep its seed while playing');
await p.evaluate(() => { st.i = 1; onTrack(true); }); await p.waitForTimeout(200);
await p.click('#rhHop'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => XP.trail.length === 2 && XP.pin === XP.trail[1] && XP.seed === XP.pin))) fail('Hop must extend the Rabbit hole trail and re-seed Go from');
const before = await p.evaluate(() => st.src); await p.click('#rhSave'); await p.waitForTimeout(150);
if (!(await p.evaluate(b => st.src === b && XP.saved.some(x => x.k.startsWith('rh_')) && !!document.querySelector('.li.svd'), before))) fail('Save as playlist must add a playlist without changing playback');
await p.evaluate(() => { st.i = SRC[st.src].q.length - 1; st.t = cur().d - .3; }); await p.waitForTimeout(700);
if (await p.evaluate(() => st.on)) fail('a Go-from mix must stop at its end');
await p.click('[data-tu="tempo:slow"]'); await p.click('[data-tu="voice:any"]'); await p.click('[data-tu="feel:dark"]'); await p.click('#tuSave'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => !!SRC.st_slow_any_dark && XP.saved.some(x => x.k === 'st_slow_any_dark') && /Saved/.test($('tuSave').textContent)))) fail('Save tune must save once and show Saved');
await p.click('[data-tu="tempo:any"]'); await p.click('[data-tune="st_slow_any_dark"]');
if (!(await p.evaluate(() => XP.tu.tempo === 'slow' && XP.tu.feel === 'dark'))) fail('a saved tune chip must restore its dials');
await p.click('#xpIn'); await p.keyboard.type('gray');
if (!(await p.evaluate(() => document.body.classList.contains('xp-searching') && SR[0] && SR[0].t === 'Moni Gray'))) fail('search must show results in place with the best match first');
await p.keyboard.press('Escape'); await p.keyboard.type('qwzx');
if (!(await p.evaluate(() => !!document.querySelector('.sr-none')))) fail('no-results state must show');
await p.keyboard.press('Escape'); await p.keyboard.press('Escape');
if (await p.evaluate(() => document.body.classList.contains('xp-searching'))) fail('Esc twice must leave search');
await p.keyboard.press('Control+k');
if (!(await p.evaluate(() => document.activeElement.id === 'xpIn' && !$('pal').classList.contains('open')))) fail('in Explore, Ctrl+K must focus the search field');
await p.close();
/* Now Playing page (rev 7) */
p = await pg({ width: 1440, height: 900 });
await p.keyboard.press('l'); await p.waitForTimeout(300);
if (!(await p.evaluate(() => $('np').classList.contains('open') && !!document.querySelector('.npt')))) fail('L must open the Now Playing page with tabs');
await p.evaluate(() => { st.uq.push('m2'); render(); }); await p.keyboard.press('2'); await p.waitForTimeout(200);
const upn = await p.evaluate(() => [...document.querySelectorAll('#npP button.npq[data-src]')].map(e => e.dataset.src));
if (!upn.length || upn.some(x => x !== 'late')) fail('Up next must list only the active source after the user queue');
if (!(await p.evaluate(() => /Playback stops here/.test($('npP').textContent) && /Next in queue/.test($('npP').textContent)))) fail('Up next must show the user queue and the honest end of source');
await p.click('[data-uqx="0"]'); await p.waitForTimeout(100);
if (await p.evaluate(() => st.uq.length)) fail('removing from the queue must work');
await p.click('#toastBtn'); if (!(await p.evaluate(() => st.uq[0] === 'm2'))) fail('Undo must restore the queue item');
await p.keyboard.press('3'); await p.waitForTimeout(150);
const crBtn = await p.$('[data-crp]'); if (!crBtn) fail('Credits must offer Play their credits'); else { await crBtn.click(); await p.waitForTimeout(150); if (!(await p.evaluate(() => st.src.startsWith('cr_') && SRC[st.src].q.includes(curK())))) fail('Play their credits must play that person\'s songs'); }
await p.keyboard.press('Escape'); await p.waitForTimeout(200);
if (await p.evaluate(() => $('np').classList.contains('open'))) fail('Esc must close Now Playing');
await p.close();
p = await pg({ width: 390, height: 844 });
await p.click('.bar .cur'); await p.waitForTimeout(400);
if (!(await p.evaluate(() => document.body.classList.contains('np-open') && getComputedStyle(document.querySelector('.bar')).visibility === 'hidden' && getComputedStyle(document.querySelector('.npctl')).display !== 'none'))) fail('phone Now Playing must be full screen with its own controls');
const on0 = await p.evaluate(() => st.on); await p.click('.nppp'); if ((await p.evaluate(() => st.on)) === on0) fail('phone play button must toggle playback');
const bx = await p.$eval('#npSk', e => { const r = e.getBoundingClientRect(); return [r.left + r.width * .75, r.top + r.height / 2]; }); await p.mouse.click(bx[0], bx[1]);
if (Math.abs(await p.evaluate(() => st.t / cur().d) - .75) > .05) fail('phone scrubber must seek');
const npo = await p.evaluate(() => $('np').scrollWidth > $('np').clientWidth + 1); if (npo) fail('phone Now Playing must not scroll sideways');
await p.click('#npX'); await p.waitForTimeout(300); if (await p.evaluate(() => document.body.classList.contains('np-open'))) fail('close must leave Now Playing');
await p.close();
// rev 8: Journeys (D-069)
p = await pg({ width: 1440, height: 900 });
await p.click('.side .nav [data-nav=journeys]'); await p.waitForTimeout(300);
if (!(await p.evaluate(() => document.body.classList.contains('v-jv') && !!document.querySelector('#jv .jmap') && getComputedStyle($('jv')).display !== 'none'))) fail('Journeys nav must open the genre page with the map');
await p.click('.jsta[data-jart="3"]'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => JV.ai === 3 && !!document.querySelector('.jah')))) fail('map station must open the Artist Journey');
await p.click('.jah [data-jpl="3"]'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => st.src === 'journey' && st.on && curK() === 'm1'))) fail('Start must play the artist Journey from the first unheard song');
await p.evaluate(() => { ['m2', 'm3', 'm4'].forEach(k => st.jHeard.add(k)); startSrc('journey', 4); st.t = cur().d - .3; }); await p.waitForTimeout(700);
await p.evaluate(() => { st.t = cur().d - .3; }); await p.waitForTimeout(800);
const fin = await p.evaluate(() => { const G = JR.G['Hip-Hop']; return [st.on, st.src, jDone(G, G.A[3]), !!G.A[3].stamp, /stamp collected/.test($('toast').textContent), SRC.journey.q.includes(curK())]; });
if (fin[0] || fin[1] !== 'journey' || !fin[5]) fail('end of an artist must stop, never autoplay the next artist: ' + JSON.stringify(fin));
if (!fin[3] || !fin[4]) fail('finishing an artist must give a stamp + toast: ' + JSON.stringify(fin));
await p.close();
p = await pg({ width: 1440, height: 900 });
await p.evaluate(() => setView('journeys'));
const h0 = await p.evaluate(() => st.jHeard.size);
await p.click('#jv [data-skip="4"]'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => JR.G['Hip-Hop'].cur === 4))) fail('Skip ahead must move the current artist');
await p.click('#toastBtn'); await p.waitForTimeout(150);
if (!(await p.evaluate(h => JR.G['Hip-Hop'].cur === 3 && st.jHeard.size === h, h0))) fail('Undo skip must restore, progress kept');
await p.click('#jv .jh [data-src^="top_"]'); await p.waitForTimeout(300);
if (!(await p.evaluate(h => st.src.startsWith('top_') && st.jHeard.size === h && JR.G['Hip-Hop'].cur === 3, h0))) fail('Play top mix must not change Journey progress (D-038)');
await p.click('#jv .jh-a [data-jnav=picker]'); await p.waitForTimeout(250);
await p.click('.pk-t[data-pk="Jazz"]'); await p.click('[data-pace="ess"]'); await p.click('#pkGo'); await p.waitForTimeout(250);
if (!(await p.evaluate(h => JV.g === 'Jazz' && JR.G.Jazz.pace === 'ess' && JR.active === 'Jazz' && st.jHeard.size === h && JR.G.Jazz.A.every(a => jPace(JR.G.Jazz, a).length <= 5), h0))) fail('Change genre must switch Journey, apply pace, erase nothing');
await p.click('#jv [data-meet="1"]'); await p.waitForTimeout(300);
if (!(await p.evaluate(() => $('modal').classList.contains('meetm') && !st.on))) fail('Meet must open the 15 s hook and pause main playback');
await p.click('#mtGo'); await p.waitForTimeout(250);
if (!(await p.evaluate(() => st.src === jKey('Jazz', 1) && st.on && JR.G.Jazz.cur === 1))) fail('Start from Meet must make that artist current and play');
await p.fill('#jIn', 'zzzz'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => /Nothing in the Jazz Journey/.test($('jv').textContent)))) fail('Journey search must show an honest no-results state');
await p.close();
p = await pg({ width: 390, height: 844 });
await p.click('.tabs [data-tab=Journeys]'); await p.waitForTimeout(300);
if (!(await p.evaluate(() => document.body.classList.contains('v-jv') && document.querySelector('.tabs .on').dataset.tab === 'Journeys'))) fail('Journeys tab must open Journeys');
for (const ai of [null, 3]) { await p.evaluate(a => setView('journeys', { ai: a ?? undefined }), ai); await p.waitForTimeout(200);
  const o = await p.evaluate(() => document.documentElement.scrollWidth > innerWidth || $('main').scrollWidth > $('main').clientWidth + 1); if (o) fail('Journeys must not scroll sideways at 390px (ai=' + ai + ')'); }
await p.close();

// rev 9: stamps, passport, share (D-070)
p = await pg({ width: 1440, height: 900 });
await p.evaluate(() => setView('journeys'));
await p.click('#jv .jstamps [data-stamp="Hip-Hop|0"]'); await p.waitForTimeout(250);
if (!(await p.evaluate(() => $('modal').classList.contains('stampm') && /Early ear/.test($('modal').textContent) && /No\. 1,284/.test($('modal').textContent) && /New since you finished/.test($('modal').textContent)))) fail('stamp must open with early ear, collector number and new songs');
await p.click('#smFlip'); if (!(await p.evaluate(() => $('smF').classList.contains('flip') && /Most played/.test($('smF').textContent)))) fail('Flip must show the back of the stamp');
await p.fill('#smNote', 'test note'); if (!(await p.evaluate(() => JR.notes['Hip-Hop|0'] === 'test note'))) fail('note must save');
await p.click('#smPin'); if (!(await p.evaluate(() => !JR.pins.includes('Hip-Hop|0')))) fail('Pinned must unpin');
await p.click('#smPin'); if (!(await p.evaluate(() => JR.pins.includes('Hip-Hop|0') && JR.pins.length <= 3))) fail('pin must re-pin, max 3');
await p.click('#smShare'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => $('modal').classList.contains('sharecard') && /I finished Asha North/.test($('modal').textContent) && !/2 new/.test(document.querySelector('.sc-in').innerText)))) fail('share card must show the stamp (no private new-song badge)');
await p.click('[data-fmt="square"]'); if (!(await p.evaluate(() => !!document.querySelector('.sc-pv.square')))) fail('Square format must switch');
await p.keyboard.press('Escape'); await p.waitForTimeout(200);
await p.click('#jv [data-pp]'); await p.waitForTimeout(250);
if (!(await p.evaluate(() => JV.pp && /Your passport/.test($('jv').textContent) && document.querySelectorAll('#jv .pp-pins > *').length === 3 && !!document.querySelector('#jv .pp-seals [data-seal="Lo-fi"]')))) fail('passport must show 3 pins and the Lo-fi seal');
await p.click('#jv .pp-seals [data-jg="Jazz"]'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => !JV.pp && JV.g === 'Jazz'))) fail('empty seal must open that genre');
await p.close();
p = await pg({ width: 390, height: 844 });
await p.evaluate(() => setView('journeys', { pp: true })); await p.waitForTimeout(200);
if (await p.evaluate(() => document.documentElement.scrollWidth > innerWidth || $('main').scrollWidth > $('main').clientWidth + 1)) fail('phone passport must not scroll sideways');
await p.close();
// rev 10: listening flow
p = await pg({ width: 1440, height: 900 });
await p.evaluate(() => { const k = curK(); menu(k, 300, 300); }); await p.waitForTimeout(150);
await p.click('#pop [data-mn="radio"]'); await p.waitForTimeout(300);
const rd = await p.evaluate(() => [st.src, st.on, SRC[st.src].q.length, SRC[st.src].q[0] === st.src.slice(3), new Set(SRC[st.src].q).size === SRC[st.src].q.length]);
if (!(rd[0].startsWith('rd_') && rd[1] && rd[2] <= 50 && rd[2] > 5 && rd[3] && rd[4])) fail('Start radio must play a finite, unique radio starting with the seed: ' + JSON.stringify(rd));
await p.keyboard.press('l'); await p.waitForTimeout(300); await p.keyboard.press('2'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => !/same (tempo|key|producer|genre)/.test($('npP').textContent) && /face down/.test($('npP').textContent) && document.querySelectorAll(`#npP button.npq[data-src="${st.src}"]`).length === 1 && /Playback stops here/.test($('npP').textContent)))) fail('radio Up next must keep picks a surprise (next song + face-down block, no reasons) and say where it ends');
const uq0 = await p.evaluate(() => st.uq.length);
await p.click('#npP [data-sim]'); await p.waitForTimeout(150);
if ((await p.evaluate(() => st.uq.length)) !== uq0 + 1) fail('Add similar must add to the queue');
await p.click('#toastBtn'); await p.waitForTimeout(150);
if ((await p.evaluate(() => st.uq.length)) !== uq0) fail('Add similar Undo must remove it');
await p.click('#npX'); await p.waitForTimeout(300); await p.evaluate(() => { st.uq = []; st.i = SRC[st.src].q.length - 1; st.t = cur().d - .3; st.on = true; render(); }); await p.waitForTimeout(800);
if (!(await p.evaluate(() => !st.on && $('kg').classList.contains('open')))) fail('end of a non-Journey source must stop and offer Keep going');
await p.waitForTimeout(1200); if (await p.evaluate(() => st.on)) fail('Keep going must never autostart');
await p.keyboard.press('Escape'); if (await p.evaluate(() => $('kg').classList.contains('open'))) fail('Esc must close Keep going');
await p.evaluate(() => { kgOpen(); }); await p.click('#kgR'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => st.src.startsWith('rd_') && st.on && st.i === 0 && !$('kg').classList.contains('open')))) fail('Keep going Radio must start a radio');
await p.evaluate(() => { startSrc('journey', 0); st.i = SRC.journey.q.length - 1; st.t = cur().d - .3; }); await p.waitForTimeout(800);
if (await p.evaluate(() => $('kg').classList.contains('open'))) fail('Journey end has its own boundary; Keep going must not open');
await p.close();
p = await b.newPage({ viewport: { width: 1440, height: 900 } }); p.on('pageerror', e => fail('runtime: ' + e.message));
await p.addInitScript(() => { window.DEMO = { cold: 1 }; }); await p.goto(U); await p.waitForTimeout(800);
const t0 = await p.evaluate(() => st.t);
if (!(await p.evaluate(() => !st.on && /Pick up where you left off/.test($('stCap').textContent)))) fail('cold open must show Pick up where you left off, paused');
await p.click('#bigpp'); await p.waitForTimeout(200);
if (!(await p.evaluate(t => st.on && Math.abs(st.t - t) < 2 && !/Pick up/.test($('stCap').textContent), t0))) fail('Pick up must resume at the same spot');
await p.close();
p = await pg({ width: 390, height: 844 });
await p.evaluate(() => { kgOpen(); }); await p.waitForTimeout(150);
if (await p.evaluate(() => { const r = $('kg').getBoundingClientRect(); return r.left < 0 || r.right > innerWidth || document.documentElement.scrollWidth > innerWidth; })) fail('phone Keep going must fit');
await p.close();
// rev 11: Playlist page + Radio page
p = await pg({ width: 1440, height: 900 });
await p.click('#pls .li[data-src="sunday"]'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => XP.view === 'src' && PV.id === 'sunday' && st.src === 'late' && document.querySelectorAll('#pv .pv-l .pv-r').length === SRC.sunday.q.length))) fail('sidebar playlist must open its page without changing playback');
await p.click('#pv [data-pvi="2"]'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => st.src === 'sunday' && st.i === 2 && st.on && document.querySelector('#pv .pv-r.on[data-pvi="2"]')))) fail('playlist row must play that song from the playlist');
await p.click('#pvPP'); if (await p.evaluate(() => st.on)) fail('playlist play button must pause when playing');
const n0 = await p.evaluate(() => SRC.sunday.q.length);
await p.click('#pv [data-pvadd]'); await p.waitForTimeout(150);
if ((await p.evaluate(() => SRC.sunday.q.length)) !== n0 + 1) fail('Add songs that fit must add to the playlist');
await p.click('#toastBtn'); await p.waitForTimeout(150);
if ((await p.evaluate(() => SRC.sunday.q.length)) !== n0) fail('Add songs that fit Undo must remove it');
await p.evaluate(() => setView('home')); await p.waitForTimeout(150);
if (await p.evaluate(() => document.body.classList.contains('v-pv'))) fail('Home must leave the playlist page');
await p.evaluate(() => startRadio('night')); await p.waitForTimeout(150);
await p.evaluate(() => setView('src', { id: st.src })); await p.waitForTimeout(200);
const rp = await p.evaluate(() => [document.querySelectorAll('#pv .rd-c.up').length, document.querySelectorAll('#pv .rd-c.dn').length, SRC[st.src].name, /same (tempo|key|producer)/.test($('pv').textContent)]);
if (!(rp[0] === 2 && rp[1] === 48 && rp[2] === 'Night Transit radio' && !rp[3])) fail('radio page must show now + next, rest face down, no reasons: ' + JSON.stringify(rp));
await p.click('#pv .rd-c.dn[data-rdc="9"]'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => PV.peek.has(9) && !!document.querySelector('#pv .rd-c.up[data-rdc="9"]') && st.i === 0))) fail('tap a face-down card must peek, not play');
await p.click('#pv .rd-c[data-rdc="9"]'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => st.i === 9 && st.on && document.querySelectorAll('#pv .rd-c.up').length >= 11))) fail('tap a peeked card must play it; earlier songs turn over');
const rdBefore = await p.evaluate(() => SRC[st.src].q.slice());
await p.click('#rdSpin'); await p.waitForTimeout(150);
const sp = await p.evaluate(b => { const q = SRC[st.src].q; return [q.length === b.length, JSON.stringify(q.slice(0, 10)) === JSON.stringify(b.slice(0, 10)), JSON.stringify(q) !== JSON.stringify(b), new Set(q).size === q.length, st.i]; }, rdBefore);
if (!(sp[0] && sp[1] && sp[2] && sp[3] && sp[4] === 9)) fail('New spin must keep played songs, re-pick the rest, same length, unique: ' + JSON.stringify(sp));
await p.click('#toastBtn'); await p.waitForTimeout(150);
if (!(await p.evaluate(b => JSON.stringify(SRC[st.src].q) === JSON.stringify(b), rdBefore))) fail('New spin Undo must restore');
await p.click('#rdAll'); if (!(await p.evaluate(() => !document.querySelector('#pv .rd-c.dn')))) fail('Show all must turn every card over');
await p.click('#rdSave'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => XP.saved.some(x => SRC[x.k] && SRC[x.k].name === 'Night Transit radio' && SRC[x.k].q.length === 50)))) fail('Save as playlist must save the radio');
await p.close();
p = await pg({ width: 390, height: 844 });
for (const go of [() => setView('src', { id: 'late' }), () => { startRadio('night'); setView('src', { id: st.src }); }]) {
  await p.evaluate(go); await p.waitForTimeout(200);
  if (await p.evaluate(() => document.documentElement.scrollWidth > innerWidth || $('main').scrollWidth > $('main').clientWidth + 1)) fail('phone playlist/radio page must not scroll sideways');
}
await p.click('#pv [data-pvback]'); if (await p.evaluate(() => XP.view === 'src')) fail('phone Back must leave the page');
await p.close();
// rev 12: Artist page
p = await pg({ width: 1440, height: 900 });
await p.evaluate(() => { const k = curK(); menu(k, 300, 300); }); await p.click('#pop [data-mn="artist"]'); await p.waitForTimeout(200);
const av0 = await p.evaluate(() => [XP.view, AV.n, st.src, document.querySelectorAll('#av .av-pop .pv-r').length, /monthly listeners/.test($('av').textContent), !!document.querySelector('#av [data-avj]')]);
if (!(av0[0] === 'artist' && av0[1] === 'Kairo Vale' && av0[2] === 'late' && av0[3] === 5 && av0[4] && av0[5])) fail('Go to artist must open the Artist page (5 popular, Journey card) without changing playback: ' + JSON.stringify(av0));
await p.click('#avPP'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => st.src === 'ap_KairoVale' && st.on && SRC[st.src].q.length <= 10))) fail('artist Play must play their popular songs');
await p.click('#avPP'); if (await p.evaluate(() => st.on)) fail('artist Play must pause when playing');
await p.click('#avMore'); if ((await p.evaluate(() => document.querySelectorAll('#av .av-pop .pv-r').length)) !== 10) fail('Show more must show 10');
await p.click('#avFol'); if (await p.evaluate(() => FOL.has('Kairo Vale'))) fail('Following must unfollow');
await p.click('#toastBtn'); if (!(await p.evaluate(() => FOL.has('Kairo Vale')))) fail('Unfollow Undo must restore');
const r0 = await p.evaluate(() => document.querySelector('#av [data-avr]').dataset.avr);
await p.click('#av .av-g [data-avr] .av-pp', { force: true }); await p.waitForTimeout(150);
if (!(await p.evaluate(r => st.src === r && st.on && XP.view === 'artist', r0))) fail('release card play button must play the release');
await p.click('[data-avf="EP"]'); if (await p.evaluate(() => [...document.querySelectorAll('#av .av-g [data-avr] > span:last-child')].some(e => !/\u00b7 EP\b/.test(e.textContent)))) fail('EP filter must show only EPs');
await p.click('#avRd'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => st.src === 'rda_KairoVale' && SRC[st.src].name === 'Kairo Vale radio' && SRC[st.src].q.length <= 50))) fail('Artist radio must start a finite artist radio');
await p.click('#av [data-avn]'); await p.waitForTimeout(150);
if (await p.evaluate(() => AV.n === 'Kairo Vale' || XP.view !== 'artist')) fail('similar artist must open their page');
await p.click('#av [data-avj]'); await p.waitForTimeout(200);
if (!(await p.evaluate(() => XP.view === 'journeys' && JV.ai !== null && !!$('jArt')))) fail('Journey card must open the Artist Journey, which links back');
await p.click('#jArt'); await p.waitForTimeout(150);
if (!(await p.evaluate(() => XP.view === 'artist'))) fail('Artist page link from the Artist Journey must work');
await p.evaluate(() => { palOpen(); $('palIn').value = 'Asha'; palRender(); }); await p.waitForTimeout(100);
await p.evaluate(() => { const i = res.findIndex(x => x.artist); palGo(i); }); await p.waitForTimeout(150);
if (!(await p.evaluate(() => XP.view === 'artist' && AV.n === 'Asha North'))) fail('search artist result must open the Artist page');
await p.close();
p = await pg({ width: 390, height: 844 });
await p.evaluate(() => artOpen('Asha North')); await p.waitForTimeout(200);
if (await p.evaluate(() => document.documentElement.scrollWidth > innerWidth || $('main').scrollWidth > $('main').clientWidth + 1)) fail('phone Artist page must not scroll sideways');
await p.close();
// rev 12.1: Artist final touches
p = await pg({ width: 1440, height: 900 });
await p.evaluate(() => artOpen('Asha North')); await p.waitForTimeout(200);
await p.evaluate(() => { $('main').style.scrollBehavior = 'auto'; $('main').scrollTop = 900; $('main').dispatchEvent(new Event('scroll')); }); await p.waitForTimeout(150);
if (!(await p.evaluate(() => $('av').classList.contains('stk')))) fail('sticky artist bar must show after scrolling past the header');
await p.evaluate(() => { $('main').scrollTop = 0; $('main').dispatchEvent(new Event('scroll')); });
await p.click('#avBell'); if (await p.evaluate(() => NOTI.has('Asha North'))) fail('bell must turn off release alerts');
await p.click('#avOpt'); await p.click('#pop [data-avm="nfm"]'); await p.waitForTimeout(100);
const nf = await p.evaluate(() => [NFM.has('Asha North'), !!document.querySelector('#av .av-nfm'), radioPicks('night', 60).some(x => S[x.k].ar === 'Asha North')]);
if (!(nf[0] && nf[1] && !nf[2])) fail('Not for me must hide the artist from radio picks and show a banner: ' + JSON.stringify(nf));
await p.click('#avNfmU'); if (await p.evaluate(() => NFM.has('Asha North'))) fail('Not for me Undo must restore');
if (!(await p.evaluate(() => /You and Asha/.test($('av').textContent) && /heard/.test(document.querySelector('#av .av-g').textContent)))) fail('You and <artist> card + heard on releases must show');
await p.click('#avLk'); await p.waitForTimeout(100);
if (!(await p.evaluate(() => st.src === 'al_AshaNorth' && SRC[st.src].q.every(k => st.liked.has(k) && S[k].ar === 'Asha North')))) fail('Play your liked songs must play only liked songs by the artist');
await p.close();
// rev 13: Release page
p = await pg({ width: 1440, height: 900 });
await p.evaluate(() => artOpen('Kairo Vale')); await p.waitForTimeout(150);
const rid = await p.evaluate(() => document.querySelector('#av .av-g [data-avr]').dataset.avr);
await p.click('#av .av-g [data-avr] b'); await p.waitForTimeout(150);
if (!(await p.evaluate(r => XP.view === 'release' && RV.id === r && st.src === 'late' && document.querySelectorAll('#rv .rlp-t').length === SRC[r].q.length && document.querySelectorAll('#rv .rlp-side').length === (SRC[r].q.length >= 7 ? 2 : 0), rid))) fail('release card must open the Release page (Side A/B for 7+ songs) without changing playback');
await p.click('#rvPP'); await p.waitForTimeout(100);
if (!(await p.evaluate(r => st.src === r && st.i === 0 && st.on && !X.shuf && $('rv').querySelector('.rlp-cv.out'), rid))) fail('release Play must play in order from song 1 and slide the record out');
await p.click('#rv [data-rlt="3"]'); if (!(await p.evaluate(() => st.i === 3))) fail('track row must play that track');
await p.click('#rv .pv-mo'); await p.click('#pop [data-rlmc]'); if (!(await p.evaluate(() => /Produced by/.test(document.querySelector('#rv .rlp-c').textContent)))) fail('Show credits in the song menu must expand song credits');
await p.click('#rvSave'); if (!(await p.evaluate(r => LIB.has(r), rid))) fail('Save must add to library');
await p.click('#toastBtn'); if (await p.evaluate(r => LIB.has(r), rid)) fail('Save Undo must remove');
await p.click('#rvOpt'); await p.click('#pop [data-rvm="queue"]'); if ((await p.evaluate(r => st.uq.length === SRC[r].q.length, rid)) !== true) fail('Add to queue must queue every song');
await p.evaluate(() => { st.uq = []; render(); });
await p.click('#rv [data-rlo]'); if (await p.evaluate(r => RV.id === r, rid)) fail('More from must open another release');
await p.click('#rv .rlp-ar'); if (!(await p.evaluate(() => XP.view === 'artist'))) fail('artist link must open the Artist page');
await p.close();
p = await pg({ width: 390, height: 844 });
await p.evaluate(() => relOpen('silver')); await p.waitForTimeout(200);
if (await p.evaluate(() => document.documentElement.scrollWidth > innerWidth || $('main').scrollWidth > $('main').clientWidth + 1)) fail('phone Release page must not scroll sideways');
await p.close();
// rev 14: sidebar + Now Playing About (D-078, D-079)
p = await pg({ width: 1440, height: 900 });
await p.click('#sbJ [data-sbjp]'); await p.waitForTimeout(100);
if (!(await p.evaluate(() => { const G = JR.G[JR.active]; return jState(JR.active, G.cur).live && st.on && !!document.querySelector('#sbJ .sbj.live'); }))) fail('sidebar Journey Play must start the Journey');
if (!(await p.evaluate(() => !!document.querySelector('#sbJ .sbjp')))) fail('live Journey card must show a progress line');
await p.click('#sbJ [data-sbjp]'); if (await p.evaluate(() => st.on)) fail('sidebar Journey Play must pause when live');
if (!(await p.evaluate(() => !!document.querySelector('#sbF .sbf-a.nw[data-sbf="Asha North"]')))) fail('followed artist with new music must have a ring');
await p.click('#sbF [data-sbf="Asha North"]'); await p.waitForTimeout(100);
if (!(await p.evaluate(() => XP.view === 'artist' && !document.querySelector('#sbF .sbf-a.nw[data-sbf="Asha North"]')))) fail('opening a ringed artist must open the Artist page and clear the ring');
await p.click('#sbJ [data-sbj]'); if (!(await p.evaluate(() => XP.view === 'journeys'))) fail('Journey card must open Journeys');
await p.evaluate(() => { startSrc('late', 0); });
if (!(await p.evaluate(() => !!document.querySelector('#pls .li.on[data-src=late]')))) fail('playing playlist row must be marked on');
if (await p.evaluate(() => document.querySelector('#repeat .it, #repeat > *').getBoundingClientRect().height > 400)) fail('On repeat cards must keep their size (class collision)');
if (!(await p.evaluate(() => { const r = document.querySelector('#pls .li.sbp[data-src=late]'); return r && parseFloat(r.style.getPropertyValue('--p')) >= 0; }))) fail('playing playlist must show a progress line');
if (!(await p.evaluate(() => document.querySelectorAll('#sbRec [data-rec]').length >= 1))) fail('Recently played must list recent sources');
{ const before = await p.evaluate(() => st.pl.sunday.length); const k = await p.evaluate(() => document.querySelector('#repeat .it[data-k]').dataset.k);
  await p.evaluate(k => { st.pl.sunday = st.pl.sunday.filter(x => x !== k); buildSide(); render(); }, k);
  const b0 = await p.evaluate(() => st.pl.sunday.length);
  await p.click('.side [data-nav=home]'); await p.waitForTimeout(200); await p.evaluate(k => document.querySelector('#repeat .it[data-k="' + k + '"]').scrollIntoView({block:'center'}), k);
  await p.dragAndDrop('#repeat .it[data-k="' + k + '"]', '#pls .li[data-src=sunday]'); await p.waitForTimeout(150);
  if (!(await p.evaluate(([k, b0]) => st.pl.sunday.length === b0 + 1 && st.pl.sunday.includes(k), [k, b0]))) fail('dragging a song onto a playlist must add it');
  await p.click('#toastBtn'); if (await p.evaluate(([k]) => st.pl.sunday.includes(k), [k])) fail('drop-to-add Undo must remove it'); }
await p.click('#sbT'); if (!(await p.evaluate(() => document.body.classList.contains('sb-mini') && document.querySelector('.side').getBoundingClientRect().width < 90))) fail('collapse button must shrink the sidebar to a rail');
if (!(await p.evaluate(() => [...document.querySelectorAll('#sbF .sbf-a')].filter(e => e.offsetParent).length <= 3 && !!document.querySelector('#sbF .sbmore').offsetParent))) fail('collapsed rail must show at most 3 artists plus +N');
{ const k2 = await p.evaluate(() => document.querySelector('#repeat .it[data-k]').dataset.k);
  await p.dragAndDrop('#repeat .it[data-k="' + k2 + '"]', '.side .nav'); await p.waitForTimeout(100);
  if (await p.evaluate(() => !document.body.classList.contains('sb-mini'))) fail('collapsed sidebar must close again after the drag ends'); }
await p.evaluate(() => { DRAG = ['night']; const ev = new Event('dragenter', { bubbles: true }); document.querySelector('.side .nav').dispatchEvent(ev); });
if (await p.evaluate(() => document.body.classList.contains('sb-mini'))) fail('dragging over a collapsed sidebar must open it');
await p.evaluate(() => { document.dispatchEvent(new Event('dragend')); DRAG = null; });
await p.click('#sbT'); if (await p.evaluate(() => document.body.classList.contains('sb-mini'))) fail('collapse button must expand again');
await p.evaluate(() => { const k = Object.keys(S).find(x => !S[x].ly && SRC.late.q.includes(x)) ; if (k) startSrc('late', SRC.late.q.indexOf(k)); X.npTab = 'lyrics'; npOpen(); npBuild(); });
if (await p.evaluate(() => !cur().ly || cur().gen)) { if (!(await p.evaluate(() => !!document.querySelector('.npab2') && !!document.querySelector('.npt .npt-off')))) fail('song without lyrics must open About, with Lyrics greyed out'); }
if (await p.evaluate(() => /\d+ BPM/.test(document.body.innerText))) fail('BPM numbers must not show in the main views');
await p.close();
// rev 14.4: playing rises to top, Deep cuts, Song notes (D-081)
p = await pg({ width: 1440, height: 900 });
if (!(await p.evaluate(() => { const r = document.querySelector('#plw .li[data-src=late]'); const l = document.querySelector('#plw .li[data-src=liked]'); return r.classList.contains('playtop') && r.getBoundingClientRect().top < l.getBoundingClientRect().top; }))) fail('playing playlist must rise to the top of Playlists');
if (!(await p.evaluate(() => document.querySelector('#sbF .sbf-a').dataset.sbf === S[curK()].ar || !FOL.has(S[curK()].ar)))) fail('artist playing must be first in Following');
await p.evaluate(() => startSrc('sunday', 0));
if (!(await p.evaluate(() => document.querySelector('#plw .li.playtop').dataset.src === 'sunday' && !document.querySelector('#plw .li[data-src=late]').classList.contains('playtop')))) fail('top slot must follow what is playing');
await p.evaluate(() => artOpen('Nia Vale')); await p.waitForTimeout(150);
await p.click('#av [data-deep]'); if (!(await p.evaluate(() => st.src.startsWith('dc_') && SRC[st.src].q.every(k => !st.jHeard.has(k) || k === curK())))) fail('Play deep cuts must play only unheard songs');
await p.evaluate(() => { const r = document.querySelector('#barArt').getBoundingClientRect(); menu(curK(), 300, 300); });
await p.click('#pop [data-snote]'); await p.fill('#snTx', 'bus home'); await p.click('#pop [data-sns]');
if (!(await p.evaluate(() => NOTES[curK()] === 'bus home'))) fail('Add a note must save a private note');
await p.evaluate(() => { X.npTab = 'about'; npOpen(); npBuild(); });
if (!(await p.evaluate(() => /bus home/.test(document.querySelector('.npnote').textContent)))) fail('note must show in Now Playing About');
await p.close();
// rev 15: Moments (D-082)
p = await pg({ width: 1440, height: 900 });
if (!(await p.evaluate(() => !!document.querySelector('#momSec .mmc') && !!document.querySelector('#mmL .mmk')))) fail('Your moments row and moment marks on the seek bar must show');
await p.evaluate(() => { startSrc('late', 2); st.t = 130; tick(); });
const m0 = await p.evaluate(() => MOM.length);
await p.click('#momBtn');
if (!(await p.evaluate(m0 => MOM.length === m0 + 1 && MOM[0].k === curK() && MOM[0].s === 120 && MOM[0].e === 150, m0))) fail('✦ must save 30 s: 10 before, 20 after');
await p.waitForTimeout(600); await p.click('#momBtn'); if (await p.evaluate(m0 => MOM.length !== m0 + 1, m0)) fail('tapping again inside the moment must not duplicate');
await p.evaluate(() => { st.t = 3; tick(); }); await p.keyboard.press('m');
if (!(await p.evaluate(m0 => MOM.length === m0 + 2 && MOM[0].s === 0 && MOM[0].e === 30, m0))) fail('M must save a moment, clamped at song start');
await p.click('#toastBtn'); if (await p.evaluate(m0 => MOM.length !== m0 + 1, m0)) fail('moment Undo must remove it');
await p.click('#momSec [data-mmall]'); await p.waitForTimeout(300);
if (!(await p.evaluate(() => st.src === 'moments' && st.i === 0 && st.t >= SRC.moments.clips[0].s && st.t < SRC.moments.clips[0].e))) fail('Play all must start at the first moment');
await p.evaluate(() => { st.t = SRC.moments.clips[0].e; }); await p.waitForTimeout(400);
if (!(await p.evaluate(() => st.i === 1 && Math.abs(st.t - SRC.moments.clips[1].s) < 1))) fail('moments must jump to the next moment when one ends');
await p.close();
// rev 15.1: remove moments + artist moments
p = await pg({ width: 1440, height: 900 });
await p.evaluate(() => { const m = MOM[0]; const i = Object.keys(SRC).find(s => SRC[s].q && SRC[s].q.includes(m.k) && s !== 'moments'); startSrc(i, SRC[i].q.indexOf(m.k)); st.t = m.s + 5; tick(); });
await p.waitForTimeout(400);
if (await p.evaluate(() => document.querySelector('#momBtn').classList.contains('in'))) fail('✦ must look the same inside a moment');
const n151 = await p.evaluate(() => MOM.length);
await p.click('#momBtn');
if (await p.evaluate(n => MOM.length !== n || !/Already saved/.test(document.getElementById('toast').textContent), n151)) fail('✦ inside a moment must say Already saved, not change anything');
await p.click('#toastBtn'); if (await p.evaluate(n => MOM.length !== n - 1, n151)) fail('Remove in the toast must remove the moment');
await p.click('#toastBtn'); if (await p.evaluate(n => MOM.length !== n, n151)) fail('remove moment Undo must bring it back');
await p.evaluate(() => { document.getElementById('toast').classList.remove('open'); setView('home'); });
await p.click('#momSec [data-mmx="0"]');
if (await p.evaluate(n => MOM.length !== n - 1, n151)) fail('× on a Home moment card must remove it');
await p.click('#toastBtn');
await p.evaluate(() => artOpen('Kairo Vale')); await p.waitForTimeout(200);
if (!(await p.evaluate(() => !!document.querySelector('[data-avmm]')))) fail('Artist You and card must show Play your moments');
await p.click('[data-avmm]'); await p.waitForTimeout(300);
if (!(await p.evaluate(() => st.src === 'moments' && SRC.moments.q.every(k => S[k].a.includes('Kairo Vale'))))) fail('Play your moments must play only that artist\'s moments');
await p.close();
await b.close();
console.log(errs.length ? 'FAIL\n' + errs.join('\n') : 'PASS: Remove moments (✦ unchanged + Already saved · Remove, ×, Undo), Artist moments, Moments (save 30 s, no dupes, M key, Undo, Play all, jumps), Playing rises to top (playlist + artist), Deep cuts, Song notes, Sidebar (Journey card play/pause/open, Following ring clears, playlist row on + progress line, Recently played, drop to add + Undo, collapse/expand, rail 3 artists + more, drag opens rail, Journey progress line, On repeat size), Now Playing no-lyrics About, no BPM, Release page (open from artist, in-order play + record out, track play, credits, Save/Undo, queue, More from, artist link, phone), Artist final touches (sticky bar, bell, Not for me + Undo, You and, liked), Artist page (open from menu/search/Journey, play/pause, more, follow/Undo, releases + filter, artist radio, similar, Journey both ways, phone), Playlist page (open, row play, pause, Add songs that fit/Undo, phone), Radio page (face down, peek, play, New spin/Undo, Show all, Save), Listening flow (Start radio, radio surprise + finite, Add similar/Undo, Keep going no-autostart/Esc/Radio, Journey end no card, Pick up resume, phone), Stamps + passport + share, Journeys (map, artist page, end stops + stamp, skip/undo, top mix, picker + pace, Meet, search, phone), scrubber, Dig flow, Undo, end-of-stack, Play Dug, source end stops, phone chrome, Explore tab + overflow, Dig from Explore, Tune a mix, Go from, Rabbit hole, Save tune, search page, Now Playing (tabs, Up next, queue remove/Undo, credits, phone controls)');
process.exit(errs.length ? 1 : 0);
